### ISSUE TITLE
[feature/project-action] create actions add issue to project

### ISSUE THREAD

**Issue by hannbyul** [hannbyul/upand#6]
Use [this template](https://github.com/actions/add-to-project) to add issues automatically

**Example**
```yml
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/<user id>/projects/<project id>
          github-token: ${{ secrets.PAT }}
```
